/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Fri Nov  2 18:23:03 2018. */

#include "babel.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sensor_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Sensor, sensor, sensor, 0),
    PB_FIELD(  2, FIXED32 , SINGULAR, STATIC  , OTHER, Sensor, drive_type, sensor, 0),
    PB_FIELD(  3, FIXED32 , SINGULAR, STATIC  , OTHER, Sensor, id, drive_type, 0),
    PB_LAST_FIELD
};

const pb_field_t PromMessage_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, PromMessage, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, PromMessage, page, type, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, PromMessage, payload, page, 0),
    PB_LAST_FIELD
};

const pb_field_t SerialMessage_fields[2] = {
    PB_FIELD(  1, UENUM   , REPEATED, STATIC  , FIRST, SerialMessage, action, action, 0),
    PB_LAST_FIELD
};





/* @@protoc_insertion_point(eof) */
