/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sat Jan 26 19:37:23 2019. */

#include "babel.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sensor_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, Sensor, sensor, sensor, 0),
    PB_FIELD(  2, FIXED32 , SINGULAR, STATIC  , OTHER, Sensor, drive_type, sensor, 0),
    PB_FIELD(  3, FIXED32 , SINGULAR, STATIC  , OTHER, Sensor, id, drive_type, 0),
    PB_LAST_FIELD
};

const pb_field_t PromMessage_fields[4] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, PromMessage, type, type, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, PromMessage, page, type, 0),
    PB_FIELD(  3, BYTES   , SINGULAR, STATIC  , OTHER, PromMessage, payload, page, 0),
    PB_LAST_FIELD
};

const pb_field_t SerialMessage_fields[2] = {
    PB_FIELD(  1, UENUM   , REPEATED, STATIC  , FIRST, SerialMessage, action, action, 0),
    PB_LAST_FIELD
};

const pb_field_t transferMetadata_fields[3] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, transferMetadata, crc, crc, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, transferMetadata, length, crc, 0),
    PB_LAST_FIELD
};

const pb_field_t programTransfer_fields[5] = {
    PB_FIELD(  1, UENUM   , SINGULAR, STATIC  , FIRST, programTransfer, action, action, 0),
    PB_ONEOF_FIELD(action_type,   2, BYTES   , ONEOF, STATIC  , OTHER, programTransfer, payload, action, 0),
    PB_ONEOF_FIELD(action_type,   3, UINT32  , ONEOF, STATIC  , UNION, programTransfer, crc, action, 0),
    PB_ONEOF_FIELD(action_type,   4, UINT32  , ONEOF, STATIC  , UNION, programTransfer, length, action, 0),
    PB_LAST_FIELD
};






/* @@protoc_insertion_point(eof) */
